ALTER TABLE  responsavel
	ADD data_nascimento DATE,
	ADD nacionalidade VARCHAR(30),
	ADD cpf VARCHAR(13),
	ADD identidade VARCHAR(30),
	ADD identidade_emissao DATE,
	ADD identidade_emissor VARCHAR(30),
	ADD identidade_estado VARCHAR(20),
	ADD religiao VARCHAR(30),
	ADD escolaridade VARCHAR(30),
	ADD profissao VARCHAR(30),
	ADD empresa VARCHAR(30),
	ADD funcao VARCHAR(30),
	ADD endereco_comercial VARCHAR(80),
	ADD telefone_comercial VARCHAR(20),
	ADD cor VARCHAR(20),
	ADD estado_civil VARCHAR(20),
	ADD sexo VARCHAR(15)
	;