CREATE TABLE funcionario (
	codigo BIGINT(50) PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(150) NOT NULL,
	email VARCHAR(100),
	telefone VARCHAR(20),
	celular VARCHAR(20),
	logradouro VARCHAR(50),
	numero VARCHAR(20),
	complemento VARCHAR(100),
	referencia VARCHAR(100),
	bairro VARCHAR(100),
	cep VARCHAR(10),
	cidade VARCHAR(50),
	estado VARCHAR(50),
	data_nascimento DATE,
	nacionalidade VARCHAR(30),
	cpf VARCHAR(15),
	identidade VARCHAR(30),
	identidade_emissao DATE,
	identidade_emissor VARCHAR(30),
	identidade_estado VARCHAR(20),	
	pis VARCHAR(50),
	carteira_trabalho VARCHAR(50),
	carteira_trabalho_serie VARCHAR(10),
	carteira_trabalho_emissao DATE,
	carteira_trabalho_estado VARCHAR(50),
	admissao DATE,
	demissao DATE,
	salario DECIMAL(10,2),
	observacao TEXT,	
	conjuge VARCHAR(100),
	naturalidade VARCHAR(50),
	naturalidade_estado VARCHAR(30),
	mae VARCHAR(50),
	pai VARCHAR(50),
	ativo BOOLEAN,
	professor BOOLEAN,	
	religiao VARCHAR(30),
	escolaridade VARCHAR(30),
	profissao VARCHAR(30),
	funcao VARCHAR(30),
	cor VARCHAR(20),
	estado_civil VARCHAR(20),
	sexo VARCHAR(15),
	tipo_sanguineo VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;